### ISSUE TITLE
No module named 'ssw_wrapper'

### ISSUE THREAD

**Issue by haojiunlo** [kyu999/ssw_aligner#1]
Hi
I try to run the demo code, but can't import the module.

**Comment by kyu999** [comment]
Hello
Could you let me know your environment like OS, python version, etc.. ?
Also, please put the error message here for debug.
By the way, installation by running the setup.py is another choice as follows.

```
git clone https://github.com/kyu999/ssw_aligner.git
cd ssw_aligner
python setup.py install
```

**Comment by kyu999** [comment]
I would like to figure out installed modules, so please copy and paste the output of this command.

```
pip list
```

**Comment by haojiunlo** [comment]
>>> import ssw_aligner
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hao/.pyenv/versions/py3.6/lib/python3.6/site-packages/ssw_aligner/__init__.py", line 1, in <module>
    from ssw_wrapper import StripedSmithWaterman
ModuleNotFoundError: No module named 'ssw_wrapper'

and my os and python version is ubuntu16.04, python3.6

**Comment by kyu999** [comment]
Although README describes that Python3 is available, it was actually not. Sorry.
I've changed README already.
I will fix and make python3 available near future.
